### ISSUE TITLE
minor documentation update

### ISSUE THREAD

**Issue by danielmotaleite** [detailyang/lua-resty-cors#6]
Sorry to nag you again! :smile:  

Just to remind you to update the readme, to change:

`It shoule be placed on the nginx init phase and run at header phase as the following:`

To something like

`It may be placed on the nginx http block for a global CORS config or in each server block to configure a different CORS for each virtual host as the following:`

And, in the example, put everything back in the header_filter_by_lua_block. Or give 2 examples, one in the http with init and header_filter and another with server block with everything in the header_filter

Many thanks for this module and for the help!

**Comment by detailyang** [comment]
@danielmotaleite You guys are cool, can you send a PR to it?

**Comment by detailyang** [comment]
done
